#ifndef PAQ8PX_CHARACTERNAMES_HPP
#define PAQ8PX_CHARACTERNAMES_HPP

#define TAB 0x09
#define NEW_LINE 0x0A
#define CARRIAGE_RETURN 0x0D
#define SPACE 0x20
#define QUOTE 0x22
#define APOSTROPHE 0x27
#define GRAVE_ACCENT 0x60

#endif //PAQ8PX_CHARACTERNAMES_HPP